### ISSUE TITLE
Documentation for Github.jl asks for authentication 

### ISSUE THREAD

**Issue by ViralBShah** [JuliaDocs/DocumentationGenerator.jl#28] opened 2019-04-17 02:48 UTC
Search for GitHub.jl and click on the documentation. It throws an authentication box.

![Screen Shot 2019-04-16 at 10 48 27 PM](https://user-images.githubusercontent.com/744411/56257301-c43b6380-6099-11e9-806a-7626c5716e08.png)

**Comment by vdayanand** [comment] 2019-04-19 15:43
This was caused by reference to path in earlier to old pkg.julialang.org in README's, for eg `pkg.julialang.org/?pkg=Github`

This is fixed now

**Closed** 2019-04-24 07:16 UTC
